DICT_PATH_VAGABOND_IMG = {
    0 : "assets/Vagabond/0-Simple Passant.png",
    1 : "assets/Vagabond/1-Errant Solitaire.png",
    2 : "assets/Vagabond/2-Voyageur fatigué.png",
    3 : "assets/Vagabond/3-Marcheur égaré.png",
    4 : "assets/Vagabond/4-Marcheur Solitaire.png",
    5 : "assets/Vagabond/5-Chiffonnier des routes.png",
    6 : "assets/Vagabond/6-Conteur des carrefours.png",
    7 : "assets/Vagabond/7-Nomade.png",
    8 : "assets/Vagabond/8-Rôdeur des bois.png",
    9 : "assets/Vagabond/9-Messager oublié.png",
    10 : "assets/Vagabond/10-Voyageur sans attaches.png",
    11 : "assets/Vagabond/11-Pélerin des bourgs.png",
    12 : "assets/Vagabond/12-Passeur de Frontière.png",
    13 : "assets/Vagabond/13-Vagabond insaisissable.png",
    14 : "assets/Vagabond/14-Pieds Poussière.png",
    15 : "assets/Vagabond/15-Dormeur sous les étoiles.png",
    16 : "assets/Vagabond/16-Ombre des routes.png",
    17 : "assets/Vagabond/17-Explorateur des Terres Sauvages.png",
    18 : "assets/Vagabond/18-Pèlerin des Sentiers Oubliés.png",
    19 : "assets/Vagabond/19-Nomade du Vent.png",
    20 : "assets/Vagabond/20-Guide des brumes.png",
    21 : "assets/Vagabond/21-Vagabond Légendaire.png",
    22 : "assets/Vagabond/22-Marcheur Celeste.png",
    23 : "assets/Vagabond/23-Maître des chemins.png"
}
